TraSuaWeb/Areas/Admin/Controllers/GioiThieuxController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TraSuaWeb.Models;
using webtrasua.helper;

namespace TraSuaWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class GioiThieuxController : Controller
    {
        private readonly DBtrasuaContext _context;

        public GioiThieuxController(DBtrasuaContext context)
        {
            _context = context;
        }

        // GET: Admin/GioiThieux
        public async Task<IActionResult> Index()
        {
            return View(await _context.GioiThieus.ToListAsync());
        }

        // GET: Admin/GioiThieux/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gioiThieu = await _context.GioiThieus
                .FirstOrDefaultAsync(m => m.IdGt == id);
            if (gioiThieu == null)
            {
                return NotFound();
            }

            return View(gioiThieu);
        }

        // GET: Admin/GioiThieux/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/GioiThieux/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdGt,TieuDe,Anh,MoTa")] GioiThieu gioiThieu, Microsoft.AspNetCore.Http.IFormFile fAnhGt)
        {
            if (ModelState.IsValid)
            {
                gioiThieu.TieuDe = Utilities.ToTitleCase(gioiThieu.TieuDe);
                if (fAnhGt != null)
                {
                    string extension = Path.GetExtension(fAnhGt.FileName);

                    string filename = $"{Utilities.SEOUrl(gioiThieu.TieuDe) }{extension}";
                    gioiThieu.Anh = filename;
                    string pathFile = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "AnhGioiThieu", filename);
                    using (var stream = new FileStream(pathFile, FileMode.Create))
                    {
                        await fAnhGt.CopyToAsync(stream);
                    }
                }
                if (string.IsNullOrEmpty(gioiThieu.Anh)) gioiThieu.Anh = "default.jpg";
                _context.Add(gioiThieu);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(gioiThieu);
        }

        // GET: Admin/GioiThieux/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gioiThieu = await _context.GioiThieus.FindAsync(id);
            if (gioiThieu == null)
            {
                return NotFound();
            }
            return View(gioiThieu);
        }

        // POST: Admin/GioiThieux/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdGt,TieuDe,Anh,MoTa")] GioiThieu gioiThieu)
        {
            if (id != gioiThieu.IdGt)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(gioiThieu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GioiThieuExists(gioiThieu.IdGt))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(gioiThieu);
        }

        // GET: Admin/GioiThieux/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var gioiThieu = await _context.GioiThieus
                .FirstOrDefaultAsync(m => m.IdGt == id);
            if (gioiThieu == null)
            {
                return NotFound();
            }

            return View(gioiThieu);
        }

        // POST: Admin/GioiThieux/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gioiThieu = await _context.GioiThieus.FindAsync(id);
            _context.GioiThieus.Remove(gioiThieu);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GioiThieuExists(int id)
        {
            return _context.GioiThieus.Any(e => e.IdGt == id);
        }
    }
}

TraSuaWeb/Areas/Admin/Views/GioiThieux/Create.cshtml
@model TraSuaWeb.Models.GioiThieu

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section Styles{
    <link href="~/Admin/assets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/Admin/assets/summernote/summernote.css" rel="stylesheet" />
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="GioiThieux" asp-action="index">Quản lý tin tức</a>
            <span class="breadcrumb-item active">Thêm tin tức</span>
        </nav>
    </div>
</div>
<form asp-area="Admin" asp-controller="GioiThieux" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tiêu đề</label>
                        <input type="text" class="form-control" asp-for="TieuDe">
                    </div>
                    <div class="form-group">
                        <label asp-for="Anh" class="control-label">Ảnh Tin Tức</label>
                        <input type="file" name="fAnhGt" id="fAnhGt" class="form-control" />
                        <span asp-validation-for="Anh" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <textarea class="summernote" asp-for="MoTa"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="lưu" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>
    </div>
</form>
@section Scripts{
    <script src="~/Admin/assets/vendors/select2/select2.min.js"></script>
    <script src="~/Admin/assets/js/pages/e-commerce-product-edit.js"></script>

    <script src="~/Admin/assets/summernote/summernote-bs4.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.14.0/jquery.validate.min.js"></script>
    <script>
        jQuery(document).ready(function () {
            $('.summernote').summernote({
                fontNames: ['Arial', 'Arial Black', 'Comic Sans MS', 'Courier New'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 200,
                minHeight: null,
                macHeight: null,
                focus: true
            });
        });
    </script>
}

TraSuaWeb/Areas/Admin/Views/GioiThieux/Delete.cshtml
@model TraSuaWeb.Models.GioiThieu

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GioiThieu</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TieuDe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TieuDe)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MoTa)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdGt" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TraSuaWeb/Areas/Admin/Views/GioiThieux/Details.cshtml
@model TraSuaWeb.Models.GioiThieu

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>GioiThieu</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TieuDe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TieuDe)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MoTa)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdGt">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TraSuaWeb/Areas/Admin/Views/GioiThieux/Edit.cshtml
@model TraSuaWeb.Models.GioiThieu

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>GioiThieu</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdGt" />
            <div class="form-group">
                <label asp-for="TieuDe" class="control-label"></label>
                <input asp-for="TieuDe" class="form-control" />
                <span asp-validation-for="TieuDe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anh" class="control-label"></label>
                <input asp-for="Anh" class="form-control" />
                <span asp-validation-for="Anh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MoTa" class="control-label"></label>
                <input asp-for="MoTa" class="form-control" />
                <span asp-validation-for="MoTa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TraSuaWeb/Areas/Admin/Views/GioiThieux/Index.cshtml
@model IEnumerable<TraSuaWeb.Models.GioiThieu>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="GioiThieux" asp-action="index">Quản lý tin tức</a>
            <span class="breadcrumb-item active">Thêm tin tức</span>
        </nav>
    </div>
</div>
<p>
    <a asp-area="Admin" asp-controller="GioiThieux" asp-action="Create" class="btn btn-default m-r-5">Thêm mới</a>
</p>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Tiêu Đề</th>
                <th>Ảnh Tin Tức</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
<tr>
    <td>@item.TieuDe</td>
    <td>
        <div class="d-flex align-items-center">
            <img src="~/images/AnhGioiThieu/@item.Anh" width="60px">
        </div>
    </td>

    <td class="text-right">
        <a asp-area="Admin" asp-controller="Tintucs" asp-action="Edit" asp-route-id="@item.IdGt" class="btn btn-info m-r-5">Sửa</a>
        <a asp-area="Admin" asp-controller="Tintucs" asp-action="Details" asp-route-id="@item.IdGt" class="btn btn-warning m-r-5">Chi tiết</a>
        <a asp-area="Admin" asp-controller="Tintucs" asp-action="Delete" asp-route-id="@item.IdGt" class="btn btn-danger m-r-5">Xóa</a>
    </td>
</tr>
}
            }


        </tbody>
    </table>
</div>