TraSuaWeb/Areas/Admin/Controllers/AdSanPhamController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using TraSuaWeb.Models;
using webtrasua.helper;

namespace TraSuaWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdSanPhamController : Controller
    {
        private readonly DBtrasuaContext _context;

        public AdSanPhamController(DBtrasuaContext context)
        {
            _context = context;
        }

        // GET: Admin/AdSanPham
        public async Task<IActionResult> Index(int? page)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 10;
            var lssanpham = _context.SanPhams.AsNoTracking()
                .Include(s => s.MaLoaiNavigation)
                .Include(s => s.MaSizeNavigation)
                .OrderByDescending(x => x.MaSp);
            PagedList<SanPham> models = new PagedList<SanPham>(lssanpham, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;

            ViewData["MaLoai"] = new SelectList(_context.LoaiSps, "MaLoai", "TenLoai");
            ViewData["MaSize"] = new SelectList(_context.Sizes, "MaSize", "LoaiSize");
            return View(models);
        }

        // GET: Admin/AdSanPham/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams
                .Include(s => s.MaLoaiNavigation)
                .Include(s => s.MaSizeNavigation)
                .FirstOrDefaultAsync(m => m.MaSp == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // GET: Admin/AdSanPham/Create
        public IActionResult Create()
        {
            ViewData["MaLoai"] = new SelectList(_context.LoaiSps, "MaLoai", "TenLoai");
            ViewData["MaSize"] = new SelectList(_context.Sizes, "MaSize", "LoaiSize");
            return View();
        }

        // POST: Admin/AdSanPham/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaSp,MaSize,MaLoai,TenSp,AnhSp,Gia,TinhTrang,NgayTao,GiaGiam,XacNhanGiam,NgaySua,AnHien")] SanPham sanPham, Microsoft.AspNetCore.Http.IFormFile fAnhSp)
        {
            if (ModelState.IsValid)
            {
                sanPham.TenSp = Utilities.ToTitleCase(sanPham.TenSp);
                if (fAnhSp != null)
                {
                    string extension = Path.GetExtension(fAnhSp.FileName);

                    string filename = $"{Utilities.SEOUrl(sanPham.TenSp) }{extension}";
                    sanPham.AnhSp = filename;
                    string pathFile = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", filename);
                    using (var stream = new FileStream(pathFile, FileMode.Create))
                    {
                        await fAnhSp.CopyToAsync(stream);
                    }
                }
                if (string.IsNullOrEmpty(sanPham.AnhSp)) sanPham.AnhSp = "default.jpg";
                sanPham.NgayTao = DateTime.Now;
                _context.Add(sanPham);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaLoai"] = new SelectList(_context.LoaiSps, "MaLoai", "TenLoai");
            ViewData["MaSize"] = new SelectList(_context.Sizes, "MaSize", "LoaiSize");
            return View(sanPham);
        }

        // GET: Admin/AdSanPham/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams.FindAsync(id);
            if (sanPham == null)
            {
                return NotFound();
            }
            ViewData["MaLoai"] = new SelectList(_context.LoaiSps, "MaLoai", "TenLoai", sanPham.MaLoai);
            ViewData["MaSize"] = new SelectList(_context.Sizes, "MaSize", "LoaiSize", sanPham.MaSize);
            return View(sanPham);
        }

        // POST: Admin/AdSanPham/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaSp,MaSize,MaLoai,TenSp,AnhSp,Gia,TinhTrang,NgayTao,GiaGiam,XacNhanGiam,NgaySua,AnHien")] SanPham sanPham, Microsoft.AspNetCore.Http.IFormFile fAnhSp)
        {

            if (id != sanPham.MaSp)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                sanPham.TenSp = Utilities.ToTitleCase(sanPham.TenSp);
                if (fAnhSp != null)
                {
                    string extension = Path.GetExtension(fAnhSp.FileName);

                    string filename = $"{Utilities.SEOUrl(sanPham.TenSp) }{extension}";
                    sanPham.AnhSp = filename;
                    string pathFile = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", filename);
                    using (var stream = new FileStream(pathFile, FileMode.Create))
                    {
                        await fAnhSp.CopyToAsync(stream);
                    }
                }
                if (string.IsNullOrEmpty(sanPham.AnhSp)) sanPham.AnhSp = "default.jpg";
                try
                {
                    sanPham.NgaySua = DateTime.Now;
                    _context.Update(sanPham);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SanPhamExists(sanPham.MaSp))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MaLoai"] = new SelectList(_context.LoaiSps, "MaLoai", "TenLoai", sanPham.MaLoai);
            ViewData["MaSize"] = new SelectList(_context.Sizes, "MaSize", "LoaiSize", sanPham.MaSize);
            return View(sanPham);
        }

        // GET: Admin/AdSanPham/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams
                .Include(s => s.MaLoaiNavigation)
                .Include(s => s.MaSizeNavigation)
                .FirstOrDefaultAsync(m => m.MaSp == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // POST: Admin/AdSanPham/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sanPham = await _context.SanPhams.FindAsync(id);
            _context.SanPhams.Remove(sanPham);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SanPhamExists(int id)
        {
            return _context.SanPhams.Any(e => e.MaSp == id);
        }
    }
}

TraSuaWeb/Areas/Admin/Views/AdSanPham/Create.cshtml
@model TraSuaWeb.Models.SanPham

@{ ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml"; }


<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdSanPham" asp-action="index">Quản lý sản phẩm</a>
            <span class="breadcrumb-item active">Thêm sản phẩm</span>
        </nav>
    </div>
</div>
<form asp-area="Admin" asp-controller="AdSanpham" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên sản phẩm</label>
                        <input type="text" class="form-control" asp-for="TenSp">
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="productPrice">Gía</label>
                            <input type="text" class="form-control" asp-for="Gia">
                        </div>
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="productPrice">Giảm giá</label>
                            <input type="text" class="form-control" asp-for="GiaGiam">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="productCategory">Mã loại</label>
                            <select asp-for="MaLoai" class="custom-select" asp-items="ViewBag.MaLoai"></select>
                        </div>
                        <div class="form-group col-md-6">
                            <label class="font-weight-semibold" for="productCategory">Mã size</label>
                            <select asp-for="MaSize" class="custom-select" asp-items="ViewBag.MaSize"></select>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label asp-for="AnhSp" class="control-label">Hình ảnh</label>
                        <input type="file" name="fAnhSp" id="fAnhSp" class="form-control" />
                        <span asp-validation-for="AnhSp" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productStatus">Trạng thái</label>
                        <div class="form-group d-flex align-items-center">
                            <div class="switch m-r-10">
                                <input type="checkbox" asp-for="TinhTrang" checked="">
                                <label for="TinhTrang"></label>
                            </div>
                            <label>Trạng thái sản phẩm</label>
                        </div>
                        <div class="form-group d-flex align-items-center">
                            <div class="switch m-r-10">
                                <input type="checkbox" asp-for="XacNhanGiam" checked="">
                                <label for="XacNhanGiam"></label>
                            </div>
                            <label>Trạng thái giảm giá</label>
                        </div>
                        <div class="form-group d-flex align-items-center">
                            <div class="switch m-r-10">
                                <input type="checkbox" asp-for="AnHien" checked="">
                                <label for="AnHien"></label>
                            </div>
                            <label>Trạng thái ẩn hiện</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="lưu" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

TraSuaWeb/Areas/Admin/Views/AdSanPham/Delete.cshtml
@model TraSuaWeb.Models.SanPham

@{ ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml"; }

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdSanPham" asp-action="index">Danh sách sản phẩm</a>
            <span class="breadcrumb-item active">Thông tin sản phẩm: @Model.TenSp</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin sản phẩm : @Model.TenSp</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20 ">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">
                            @Model.MaSp
                        </td>
                    </tr>
                    <tr>
                        <td>Tên sản phẩm:</td>
                        <td>
                            @Model.TenSp
                        </td>
                    </tr>
                    <tr>
                        <td>ảnh sản phẩm :</td>
                        <td>
                            <img width="200" height="200" src="~/images/@Model.AnhSp" alt="" />
                        </td>
                    </tr>
                    <tr>
                        <td>Tình trạng:</td>
                        <td>
                            @Model.TinhTrang
                        </td>
                    </tr>
                    <tr>
                        <td>Trạng thái sản phẩm:</td>
                        <td>
                            @Model.TinhTrang
                        </td>
                    </tr>
                    <tr>
                        <td>Trạng thái giảm giá:</td>
                        <td>
                            @Model.XacNhanGiam
                        </td>
                    </tr>
                    <tr>
                        <td>Trạng thái ẩn hiện:</td>
                        <td>
                            @Model.AnHien
                        </td>
                    </tr>
                    <tr>
                        <td>Gía:</td>
                        <td>
                            @Model.Gia.Value.ToString("#,##0") VND
                        </td>
                    </tr>
                    <tr>
                        <td>Mã loại:</td>
                        <td>
                            @Model.MaLoaiNavigation.TenLoai
                        </td>
                    </tr>
                    <tr>
                        <td>Mã size :</td>
                        <td>
                            @Model.MaSizeNavigation.LoaiSize
                        </td>
                    </tr>
                    <tr>
                        <td>Xác nhận xóa :</td>
                        <td>
                            <form asp-action="Delete">
                                <input type="hidden" asp-for="MaSp" />
                                <input type="submit" value="Delete" class="btn btn-danger" />
                            </form>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MaSp">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TraSuaWeb/Areas/Admin/Views/AdSanPham/Details.cshtml
@model TraSuaWeb.Models.SanPham

@{ ViewData["Title"] = "Thông tin sản phẩm" + Model.TenSp;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml"; }

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdSanPham" asp-action="index">Danh sách sản phẩm</a>
            <span class="breadcrumb-item active">Thông tin sản phẩm: @Model.TenSp</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin sản phẩm : @Model.TenSp</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20 ">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">
                            @Model.MaSp
                        </td>
                    </tr>
                    <tr>
                        <td>Tên sản phẩm:</td>
                        <td>
                            @Model.TenSp
                        </td>
                    </tr>
                    <tr>
                        <td>ảnh sản phẩm :</td>
                        <td>
                            <img width="200" height="200" src="~/images/@Model.AnhSp" alt="" />
                        </td>
                    </tr>
                    <tr>
                        <td>Trạng thái sản phẩm:</td>
                        <td>
                            @Model.TinhTrang
                        </td>
                    </tr>
                    <tr>
                        <td>Trạng thái giảm giá:</td>
                        <td>
                            @Model.XacNhanGiam
                        </td>
                    </tr>
                    <tr>
                        <td>Trạng thái ẩn hiện:</td>
                        <td>
                            @Model.AnHien
                        </td>
                    </tr>
                    <tr>
                        <td>Gía :</td>
                        <td>
                            @Model.Gia.Value.ToString("#,##0") VND
                        </td>
                    </tr>
                    <tr>
                        <td>Mã loại:</td>
                        <td>
                            @Model.MaLoaiNavigation.TenLoai
                        </td>
                    </tr>
                    <tr>
                        <td>Mã size :</td>
                        <td>
                            @Model.MaSizeNavigation.LoaiSize
                        </td>
                    </tr>
                    <tr>
                        <td>Ngày tạo</td>
                        <td>
                            @Model.NgayTao
                        </td>
                    </tr>
                    <tr>
                        <td>Ngày sửa</td>
                        <td>
                            @Model.NgaySua
                        </td>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MaSp">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TraSuaWeb/Areas/Admin/Views/AdSanPham/Edit.cshtml
@model TraSuaWeb.Models.SanPham

@{
    ViewData["Title"] = "chỉnh sửa sản phẩm" + Model.TenSp;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdSanPham" asp-action="index">chỉnh sửa sản phẩm</a>
        </nav>
    </div>
</div>
<form asp-area="Admin" asp-controller="AdSanpham" asp-action="Edit" asp-route-id="@Model.MaSp" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="MaSp" />
    <input type="hidden" asp-for="AnhSp" />
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên sản phẩm</label>
                        <input type="text" class="form-control" asp-for="TenSp">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productPrice">Gía</label>
                        <input type="text" class="form-control" asp-for="Gia">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productPrice">Gía</label>
                        <input type="text" class="form-control" asp-for="GiaGiam">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productCategory">Mã loại</label>
                        <select asp-for="MaLoai" class="custom-select" asp-items="ViewBag.MaLoai"></select>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productCategory">Mã size</label>
                        <select asp-for="MaSize" class="custom-select" asp-items="ViewBag.MaSize"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="AnhSp" class="control-label">Hình ảnh</label>
                        <input type="file" name="fAnhSp" id="fAnhSp" class="form-control" />
                        <span asp-validation-for="AnhSp" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productStatus">Status</label>
                        <div class="form-group d-flex align-items-center">
                            <div class="switch m-r-10">
                                <input type="checkbox" asp-for="TinhTrang" checked="">
                                <label for="TinhTrang"></label>
                            </div>
                            <label>Checked</label>
                        </div>
                        <div class="form-group d-flex align-items-center">
                            <div class="switch m-r-10">
                                <input type="checkbox" asp-for="XacNhanGiam" checked="">
                                <label for="XacNhanGiam"></label>
                            </div>
                            <label>Trạng thái giảm giá</label>
                        </div>
                        <div class="form-group d-flex align-items-center">
                            <div class="switch m-r-10">
                                <input type="checkbox" asp-for="AnHien" checked="">
                                <label for="AnHien"></label>
                            </div>
                            <label>Trạng thái ẩn hiện</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<div>
    <a asp-action="Index">Back to List</a>
</div>

TraSuaWeb/Areas/Admin/Views/AdSanPham/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<TraSuaWeb.Models.SanPham>

@{
    int CurrenPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh sách sản phẩm" + CurrenPage;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <span class="breadcrumb-item active">Danh sách sản phẩm : page @CurrenPage</span>
        </nav>
    </div>
</div>
<p>
    <a asp-area="Admin" asp-controller="AdSanPham" asp-action="Create" class="btn btn-default m-r-5">Thêm mới</a>
</p>
<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tên sản phẩm</th>
                        <th>Anh san pham</th>

                        <th>Mã loại</th>
                        <th>Mã Size</th>
                        <th>Gía</th>
                        <th>Tình trạng</th>
                        <th>Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr role="row" class="odd">
                                <td>
                                    @item.MaSp
                                </td>
                                <td class="sorting_1">
                                    <h6 class="m-b-0 m-l-10">@item.TenSp</h6>
                                </td>
                                <td>
                                    <div class="d-flex align-items-center">
                                        <img src="~/images/@item.AnhSp" width="60px">
                                    </div>
                                </td>
                                <td>@item.MaLoaiNavigation.TenLoai</td>
                                <td>@item.MaSizeNavigation.LoaiSize</td>
                                <td>@item.Gia.Value.ToString("#,##0") VND</td>
                                <td>
                                    @if (item.TinhTrang)
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>còn</div>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-danger badge-dot m-r-10"></div>
                                            <div>hết</div>
                                        </div>
                                    }

                                </td>
                                <td class="text-right">
                                    <a asp-area="Admin" asp-controller="AdSanPham" asp-action="Edit" asp-route-id="@item.MaSp" class="btn btn-info m-r-5">Sửa</a>
                                    <a asp-area="Admin" asp-controller="AdSanPham" asp-action="Details" asp-route-id="@item.MaSp" class="btn btn-warning m-r-5">Chi tiết</a>
                                    <a asp-area="Admin" asp-controller="AdSanPham" asp-action="Delete" asp-route-id="@item.MaSp" class="btn btn-danger m-r-5">Xóa</a>
                                </td>
                            </tr>
                        }
                    }

                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdSanPham" asp-action="index" />
                </ul>
            </div>
        </div>
    </div>
</div>