TraSuaWeb/Areas/Admin/Controllers/AdKhachHangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TraSuaWeb.Models;

namespace TraSuaWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdKhachHangsController : Controller
    {
        private readonly DBtrasuaContext _context;

        public AdKhachHangsController(DBtrasuaContext context)
        {
            _context = context;
        }

        // GET: Admin/AdKhachHangs
        public async Task<IActionResult> Index()
        {
            return View(await _context.KhachHangs.ToListAsync());
        }

        // GET: Admin/AdKhachHangs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHangs
                .FirstOrDefaultAsync(m => m.MaKh == id);
            if (khachHang == null)
            {
                return NotFound();
            }

            return View(khachHang);
        }

        // GET: Admin/AdKhachHangs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdKhachHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaKh,TenKh,Sðt,DiaChi,Email,Password,Tinhtrang")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                _context.Add(khachHang);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(khachHang);
        }

        // GET: Admin/AdKhachHangs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHangs.FindAsync(id);
            if (khachHang == null)
            {
                return NotFound();
            }
            return View(khachHang);
        }

        // POST: Admin/AdKhachHangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaKh,TenKh,Sðt,DiaChi,Email,Password,Tinhtrang")] KhachHang khachHang)
        {
            if (id != khachHang.MaKh)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(khachHang);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KhachHangExists(khachHang.MaKh))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(khachHang);
        }

        // GET: Admin/AdKhachHangs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHangs
                .FirstOrDefaultAsync(m => m.MaKh == id);
            if (khachHang == null)
            {
                return NotFound();
            }

            return View(khachHang);
        }

        // POST: Admin/AdKhachHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var khachHang = await _context.KhachHangs.FindAsync(id);
            _context.KhachHangs.Remove(khachHang);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KhachHangExists(int id)
        {
            return _context.KhachHangs.Any(e => e.MaKh == id);
        }
    }
}

TraSuaWeb/Areas/Admin/Views/AdKhachHangs/Create.cshtml
@model TraSuaWeb.Models.KhachHang

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdKhachHangs" asp-action="index">Danh sách Khách Hàng</a>
            <span class="breadcrumb-item active">Thêm mới khách hàng</span>
        </nav>
    </div>
</div>
<form asp-area="Admin" asp-controller="AdKhachHangs" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên khách hàng</label>
                        <input type="text" class="form-control" asp-for="TenKh">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productPrice">Email</label>
                        <input type="text" class="form-control" asp-for="Email">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productPrice">Password</label>
                        <input type="text" class="form-control" asp-for="Password">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productPrice">Số điện thoai</label>
                        <input type="text" class="form-control" asp-for="Sðt">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productPrice">Địa chỉ</label>
                        <input type="text" class="form-control" asp-for="DiaChi">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productStatus">Trạng thái</label>
                        <div class="form-group d-flex align-items-center">
                            <div class="switch m-r-10">
                                <input type="checkbox" asp-for="Tinhtrang" checked="">
                                <label for="Tinhtrang"></label>
                            </div>
                            <label>Trạng thái tài khoản</label>
                        </div>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Lưu" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

TraSuaWeb/Areas/Admin/Views/AdKhachHangs/Delete.cshtml
@model TraSuaWeb.Models.KhachHang

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdKhachHangs" asp-action="index">Danh sách khách hàng</a>
            <span class="breadcrumb-item active">Xóa khách hàng: @Model.TenKh</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin sản phẩm : @Model.TenKh</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20 ">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">
                            @Model.MaKh
                        </td>
                    </tr>
                    <tr>
                        <td>Tên sản phẩm:</td>
                        <td>
                            @Model.TenKh
                        </td>
                    </tr>
                    <tr>
                        <td>Email: </td>
                        <td>
                            @Model.Email
                        </td>
                    </tr>
                    <tr>
                        <td>Password: </td>
                        <td>
                            @Model.Password
                        </td>
                    </tr>
                    <tr>
                        <td>Số điện thoai: </td>
                        <td>
                            @Model.Sðt
                        </td>
                    </tr>
                    <tr>
                        <td>Địa chỉ :</td>
                        <td>
                            @Model.DiaChi
                        </td>
                    </tr>
                    <tr>
                        <td>Tình trạng:</td>
                        <td>
                            @Model.Tinhtrang
                        </td>
                    </tr>
                    <tr>
                        <td>Xác nhận xóa :</td>
                        <td>
                            <form asp-action="Delete">
                                <input type="hidden" asp-for="MaKh" />
                                <input type="submit" value="Delete" class="btn btn-danger" />
                            </form>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MaKh">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TraSuaWeb/Areas/Admin/Views/AdKhachHangs/Details.cshtml
@model TraSuaWeb.Models.KhachHang

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdKhachHangs" asp-action="index">Danh sách khách hàng</a>
            <span class="breadcrumb-item active">Chi tiết khách hàng: @Model.TenKh</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin sản phẩm : @Model.TenKh</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20 ">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">
                            @Model.MaKh
                        </td>
                    </tr>
                    <tr>
                        <td>Tên sản phẩm:</td>
                        <td>
                            @Model.TenKh
                        </td>
                    </tr>
                    <tr>
                        <td>Email: </td>
                        <td>
                            @Model.Email
                        </td>
                    </tr>
                    <tr>
                        <td>Password: </td>
                        <td>
                            @Model.Password
                        </td>
                    </tr>
                    <tr>
                        <td>Số điện thoai: </td>
                        <td>
                            @Model.Sðt
                        </td>
                    </tr>
                    <tr>
                        <td>Địa chỉ :</td>
                        <td>
                            @Model.DiaChi
                        </td>
                    </tr>
                    <tr>
                        <td>Trạng thái tài khoản:</td>
                        <td>
                            @Model.Tinhtrang
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MaKh">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TraSuaWeb/Areas/Admin/Views/AdKhachHangs/Edit.cshtml
@model TraSuaWeb.Models.KhachHang

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdKhachHangs" asp-action="index">chỉnh sửa sản phẩm</a>
        </nav>
    </div>
</div>
<form asp-area="Admin" asp-controller="AdKhachHangs" asp-action="Edit" asp-route-id="@Model.MaKh" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="MaKh" />
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productName">Tên sản phẩm</label>
                        <input type="text" class="form-control" asp-for="TenKh">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productPrice">Gía</label>
                        <input type="text" class="form-control" asp-for="Email">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productPrice">Password</label>
                        <input type="text" class="form-control" asp-for="Password">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productPrice">Số điện thoại</label>
                        <input type="text" class="form-control" asp-for="Sðt">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productPrice">Địa chỉ</label>
                        <input type="text" class="form-control" asp-for="DiaChi">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" for="productStatus">Trạng thái</label>
                        <div class="form-group d-flex align-items-center">
                            <div class="switch m-r-10">
                                <input type="checkbox" asp-for="Tinhtrang" checked="">
                                <label for="Tinhtrang"></label>
                            </div>
                            <label>Trạng thái tài khoản</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<div>
    <a asp-action="Index">Back to List</a>
</div>

TraSuaWeb/Areas/Admin/Views/AdKhachHangs/Index.cshtml
@model IEnumerable<TraSuaWeb.Models.KhachHang>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdKhachHangs" asp-action="index">Danh sách Khách Hàng</a>
        </nav>
    </div>
</div>
<p>
    <a asp-area="Admin" asp-controller="AdKhachHangs" asp-action="Create" class="btn btn-default m-r-5">Thêm mới</a>
</p>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Tên khách hàng</th>
                <th scope="col">Email</th>
                @*<th scope="col">Password</th>*@
                <th scope="col">Số điện thoai</th>
                <th scope="col">Địa chỉ</th>
                <th scope="col">Tình trạng</th>
                <th scope="col">chức năng</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
            <tr>
                <th scope="row">@item.MaKh</th>
                <td>@item.TenKh</td>
                <td>@item.Email</td>
                @*<td>@item.Password</td>*@
                <td>@item.Sðt</td>
                <td>@item.DiaChi</td>
                <td>
                    @if (item.Tinhtrang)
                    {
                        <div class="d-flex align-items-center">
                            <div class="badge badge-success badge-dot m-r-10"></div>
                            <div>Còn</div>
                        </div>
                    }
                    else
                    {
                        <div class="d-flex align-items-center">
                            <div class="badge badge-danger badge-dot m-r-10"></div>
                            <div>Hết</div>
                        </div>
                    }

                </td>
                <td>
                    <a asp-area="Admin" asp-controller="AdKhachHangs" asp-action="Edit" asp-route-id="@item.MaKh" class="btn btn-info m-r-5">Sửa</a>
                    <a asp-area="Admin" asp-controller="AdKhachHangs" asp-action="Details" asp-route-id="@item.MaKh" class="btn btn-warning m-r-5">Chi tiết</a>
                    <a asp-area="Admin" asp-controller="AdKhachHangs" asp-action="Delete" asp-route-id="@item.MaKh" class="btn btn-danger m-r-5">Xóa</a>

                </td>
            </tr>
                }
            }


        </tbody>
    </table>
</div>